name: koumatsumoto/validate-semver-action
description: Action for validating whether the version string is correct according to Semantic Versioning.

inputs:
  value:
    description: "string value to be validated"
    required: true

outputs:
  raw_value:
    description: "Raw inputted value"
    value: ${{ steps.result.outputs.value }}
  version:
    description: "Coerced version string"
    value: ${{ steps.result.outputs.version }}
  coerced:
    description: "true if Output version is coerced"
    value: ${{ steps.result.outputs.coerced }}

runs:
  using: "composite"
  steps:
    - name: Extract version string
      shell: bash
      id: result
      run: echo "$(. ${GITHUB_ACTION_PATH}/main.sh ${{ inputs.value }})" >> $GITHUB_OUTPUT
